apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-sample22
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backend2
    app.kubernetes.io/part-of: application-sample2
  name: component-sample22
  namespace: application-service-system
spec:
  host: route111
  port:
    targetPort: 1111
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: component-sample22
    weight: 100
status: {}
